name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-clojure@master
      with:
        # To use Clojure CLI 1.10.1.561 based on tools.deps
        cli: '1.10.1.469'
    - name: Run tests
      run: ./scripts/test
